// MONSTER MANUAL
const GET_MONSTERS = 'GET_MONSTERS';
const GET_MONSTER = 'GET_MONSTER';

// SPELL BOOK
const GET_SPELLS = 'GET_SPELLS';
const GET_SPELL = 'GET_SPELL';

// ITEM LIST
const GET_ITEMS = 'GET_ITEMS';
const GET_ITEM = 'GET_ITEM';

// USER
const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

// FAVORITES
const GET_FAVORITES = 'GET_FAVORITES';
const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
const REM_FROM_FAVORITES = 'REM_FROM_FAVORITES';

export default {
    // MONSTER MANUAL
    GET_MONSTERS,
    GET_MONSTER,

    // SPELL BOOK
    GET_SPELLS,
    GET_SPELL,

    // ITEM LIST
    GET_ITEMS,
    GET_ITEM,

    // USER
    UPDATE_USER_INFO,

    // FAVORITES
    GET_FAVORITES,
    ADD_TO_FAVORITES,
    REM_FROM_FAVORITES
}